name: Update Deals (every 6 hours)

on:
  schedule:
    - cron: "0 */6 * * *"   # runs at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:         # allows manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated data if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/deals.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update deals.json"
      
      - name: Push changes
        if: ${{ always() }}
        run: |
          git push
